export default defineAppConfig({
  pages: [
    "pages/login/index",
    "pages/index/index",
    "pages/category/index",
    "pages/guide/index",
    "pages/profile/index",
    "pages/postDetail/PostDetail",
    "pages/createPost/index",
    "pages/createGuide/index",
    "pages/myProfileComponents/aboutUs/index",
    "pages/myProfileComponents/anonymousSetting/index",
    "pages/myProfileComponents/myAnswers/index",
    "pages/myProfileComponents/myPosted/index",
    "pages/myProfileComponents/myQuestions/index",
    "pages/myProfileComponents/mySaved/index",
    "pages/myProfileComponents/notifications/index",
    "pages/myProfileComponents/privateSecurity/index",
    "pages/myProfileComponents/reportFeedback/index",
    "pages/myProfileComponents/userSetting/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "WeChat",
    navigationBarTextStyle: "black",
  },
});
